### ISSUE TITLE
dart_sdk.js type error in Serial.getPorts() 

### ISSUE THREAD

**Issue by r3flow** [jodinathan/js_bindings#14] opened 2022-06-11 21:21 UTC
```dart
import 'package:js_bindings/js_bindings.dart';

Future<void> getPorts() async {
  final ports = await window.navigator.serial.getPorts();
  print('${ports.length}');
}
```
results in the following error message:
```dart
Error: Expected a value of type 'FutureOr<List<JavaScriptObject>>?', but got one of type 'List<dynamic>'
    at Object.throw_ [as throw] (http://localhost:54159/dart_sdk.js:5067:11)
    at Object.castError (http://localhost:54159/dart_sdk.js:5026:15)
    at Object.cast [as as] (http://localhost:54159/dart_sdk.js:5351:17)
    at dart.NullableType.new.as (http://localhost:54159/dart_sdk.js:6911:60)
    at http://localhost:54159/dart_sdk.js:62554:139
```
Flutter 2.10.5 and 3.0.2 both give the same result (pubspec.yaml "sdk" field updated accordingly to 2.16.2 or 2.17.3)

**Comment by jodinathan** [comment] 2022-06-13 12:28
this is an SDK bug that should be fixed in [2.18](https://github.com/dart-lang/sdk/issues/48835).  

The problem is with a function that returns a `Future`. For now you can copy the `getPorts()` code instead of using it.

**Closed as completed by jodinathan** 2022-06-13 12:28 UTC
